Repository Amegma/Galaxy-Attack, pull requests merged in 2021-12, with the labels that each got.

#35 feat(#31): add clickable menu text buttons
  main.py
  models/button.py
Labels: feature

#38 feat: Icon Buttons
  assets/graphics/play.png
  assets/graphics/trophy.png
  constants.py
  main.py
  models/button.py
  models/icon_button.py
  utils/outline_image.py
Labels: enhancement, v1.2.0

#25 fix(#15): game issue + add explosion animation and sounds
  .gitignore
  assets/graphics/explosion/tile000.png
  assets/graphics/explosion/tile001.png
  assets/graphics/explosion/tile002.png
  assets/graphics/explosion/tile003.png
  assets/graphics/explosion/tile004.png
  assets/graphics/explosion/tile005.png
  assets/graphics/explosion/tile006.png
  assets/graphics/explosion/tile007.png
  assets/sounds/explode.wav
  assets/sounds/laser_hit.wav
  constants.py
  main.py
  main.spec
  models/explosion.py
  models/ship.py
  screens/controls.py
  screens/game.py
  screens/score_board.py
  utils/collide.py
Labels: enhancement, v1.2.0

#41 Major Game Update (v1.2.0) 🎉
  .gitignore
  assets/graphics/audio.png
  assets/graphics/back.png
  assets/graphics/back2.png
  assets/graphics/cc06fb47b7b6942.png
  assets/graphics/e9fa4a602ed2f09.png
  assets/graphics/play.png
  assets/graphics/trophy.png
  constants.py
  main.py
  models/button.py
  models/explosion.py
  models/icon_button.py
  screens/background.py
  screens/controls.py
  screens/game.py
  screens/score_board.py
  utils/collide.py
  utils/outline_image.py
  utils/resource_path.py
Labels: v1.2.0, feature
