Repository Amegma/Galaxy-Attack, pull requests merged in 2022-10, with the labels that each got.

#67 Game Over Sound
  assets/sounds/gameover.wav
  constants.py
  screens/game.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#64 Fix(#29) Persisting user scores in Sqlite DB
  README.md
  constants.py
  models/db.py
  models/score.py
  models/scores.py
  screens/score_board.py
  utils/appdata_dir.py
  utils/assets.py
Labels: hacktoberfest, feature

#66 Playable on Linux
  config.py
Labels: hacktoberfest, hacktoberfest-accepted, feature
